Add files via upload
Trying to merge the breakalign.pl, which has corrected comments etc, with version 5.9.6 with its require rather than use SeqIO. Odd bug appearing at lines 41-53 (below)
unless ($blast_path) {
	my $blast_path = qx(which blastn);
	print "1. blast path is ".$blast_path."\n";
	$blast_path =~  s/blastn$//;
	chomp($blast_path); # remove new line character if we get blast path from 'which' system command
	$blast_path =~ s/\r\n$//; # just in case chomp does not work
	$blast_path =~ s/\r$//;# just in case...
	print "2. blast path is ".$blast_path."\n";
}
print "3. blast path is ".$blast_path."\n";
unless ($blast_path) { die "\nERROR: blastn not found"; }

Output to screen on my mac is as follows
rbelshaw@Roberts-MacBook-Air final_testing % perl breakalign_5_9_7.pl -f hg19_chr19_29855576_29856018.fa -r NGSreads.fa -vr LTR.fasta
1. blast path is /applications/ncbi-blast-2.10.1+/bin/blastn

2. blast path is /applications/ncbi-blast-2.10.1+/bin/
3. blast path is 

ERROR: 8888 blastn not found at breakalign_5_9_7.pl line 53.